#!/usr/bin/env python3
"""Generate versioned data, not a filesystem comparison algorithm.

Sources: Unicode 12.1 UCD (manifest.json), UAX #44 property definitions,
and CaseFolding.txt's C + F rule for full, non-Turkic folding.
No host Unicode library or network access is used. Canonical mappings remain
recursive; algorithmic Hangul decomposition belongs to the future consumer.
Run chore generate:casefold-unicode, or chore check:casefold-unicode to verify.
"""

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import sys


# These development commands must leave a clean checkout clean.
sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "unicode" / "12.1.0"
OUTPUT = DATA / "tables.rs"


def verify_inputs(directory):
    spec = importlib.util.spec_from_file_location(
        "unicode_integrity", ROOT / "scripts" / "check-casefold-unicode.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.verify(directory)


def records(path):
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.partition("#")[0].strip()
        if line:
            yield [field.strip() for field in line.split(";")]


def scalar(value):
    if not 0 <= value <= 0x10FFFF or 0xD800 <= value <= 0xDFFF:
        raise ValueError(f"not a Unicode scalar: {value:X}")
    return value


def mapping(text):
    result = tuple(scalar(int(value, 16)) for value in text.split())
    if not result:
        raise ValueError("empty mapping")
    return result


def bounds(text):
    parts = text.split("..")
    first, last = int(parts[0], 16), int(parts[-1], 16)
    if len(parts) > 2 or not 0 <= first <= last <= 0x10FFFF:
        raise ValueError(f"invalid code point range: {text}")
    return first, last


def ordered_ranges(rows):
    rows = sorted(rows)
    for previous, current in zip(rows, rows[1:]):
        if previous[1] >= current[0]:
            raise ValueError("overlapping property ranges")
    return rows


def read_tables(directory):
    verify_inputs(directory)
    decomposition, combining, folding = {}, {}, {}
    for row in records(directory / "UnicodeData.txt"):
        if len(row) != 15:
            raise ValueError("UnicodeData record must have 15 fields")
        cp, ccc, dm = int(row[0], 16), int(row[3]), row[5]
        if not 0 <= ccc <= 255:
            raise ValueError("combining class does not fit u8")
        if row[1].endswith((", First>", ", Last>")):
            # Every range in this pinned release has the default values.
            # Never silently lose a non-default property if inputs change.
            if ccc or dm:
                raise ValueError("non-default UnicodeData range requires expansion")
        if ccc:
            combining[scalar(cp)] = ccc
        if dm and not dm.startswith("<"):
            decomposition[scalar(cp)] = mapping(dm)

    for row in records(directory / "CaseFolding.txt"):
        cp, status, values, _ = row
        if status not in {"C", "F", "S", "T"}:
            raise ValueError(f"unknown folding status: {status}")
        if status in {"C", "F"}:
            cp = scalar(int(cp, 16))
            if cp in folding:
                raise ValueError("duplicate full folding mapping")
            folding[cp] = mapping(values)

    ignorables = ordered_ranges([
        bounds(row[0])
        for row in records(directory / "DerivedCoreProperties.txt")
        if row[1] == "Default_Ignorable_Code_Point"
    ])
    ages = []
    for span, age in records(directory / "DerivedAge.txt"):
        major, minor = (int(part) for part in age.split("."))
        if not (0 <= major <= 12 and 0 <= minor <= 255) or (major, minor) > (12, 1):
            raise ValueError("age exceeds the pinned Unicode version")
        ages.append((*bounds(span), major, minor))
    return decomposition, combining, folding, ignorables, ordered_ranges(ages)


def render(directory):
    decomposition, combining, folding, ignorables, ages = read_tables(directory)
    manifest = json.loads((directory / "manifest.json").read_text(encoding="utf-8"))
    digest = hashlib.sha256(json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    lines = [
        "// Generated by scripts/generate-casefold-unicode.py; do not edit.",
        "// Unicode data license: data/unicode/12.1.0/LICENSE.txt (Unicode-3.0).",
        f"// Canonical JSON manifest SHA-256: {digest}",
        "// Sources and per-file checksums: data/unicode/12.1.0/manifest.json.",
        "// Data only: no filesystem policy, UTF-8 validation or comparison algorithm.",
        "pub const UNICODE_VERSION: (u8, u8, u8) = (12, 1, 0);",
        "",
    ]

    def table(name, signature, rows):
        lines.append(f"pub static {name}: &{signature} = &[")
        lines.extend(f"    {row}," for row in rows)
        lines.extend(["];", ""])

    for name, entries in [
        ("CANONICAL_DECOMPOSITIONS", decomposition), ("FULL_CASE_FOLDING", folding)
    ]:
        if name == "CANONICAL_DECOMPOSITIONS":
            lines.append("// Recursive canonical mappings only; Hangul is algorithmic. Absent => identity.")
        else:
            lines.append("// Full default (C + F), excluding simple-only and Turkic mappings. Absent => identity.")
        table(name, "[(u32, &[u32])]", [
            f"(0x{cp:04X}, &[{', '.join(f'0x{x:04X}' for x in values)}])"
            for cp, values in sorted(entries.items())
        ])
    lines.append("// Nonzero canonical combining classes. Absent => class zero.")
    table("COMBINING_CLASSES", "[(u32, u8)]", [
        f"(0x{cp:04X}, {value})" for cp, value in sorted(combining.items())
    ])
    lines.append("// Inclusive ranges. Absent => not default-ignorable.")
    table("DEFAULT_IGNORABLE_RANGES", "[(u32, u32)]", [
        f"(0x{first:04X}, 0x{last:04X})" for first, last in ignorables
    ])
    lines.append("// Inclusive ranges and age (major, minor). Absent => Unassigned, NOT invalid UTF-8.")
    table("AGE_RANGES", "[(u32, u32, u8, u8)]", [
        f"(0x{first:04X}, 0x{last:04X}, {major}, {minor})"
        for first, last, major, minor in ages
    ])
    return "\n".join(lines).encode("utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=DATA)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true", help="refuse missing or stale output without writing")
    args = parser.parse_args()
    try:
        result = render(args.data_dir)
        if args.check:
            if args.output.read_bytes() != result:
                raise ValueError("stale tables; run chore generate:casefold-unicode")
        else:
            args.output.write_bytes(result)
    except (OSError, ValueError, KeyError, TypeError, IndexError) as error:
        print(f"casefold-tables: FAILED: {error}", file=sys.stderr)
        return 1
    print(f"casefold-tables: {'verified' if args.check else 'generated'} {len(result)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
